
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'aviary container registry'
    repository: 'aviary.tech'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'sed -i -e ''s/__BUILD_ID__/$(Build.BuildId)/g'' azure-deployment.yml'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'azure-deployment.yml'
    ArtifactName: 'azure-deployment.yml'