kind: Service
apiVersion: v1
metadata:
  name: aviary-tech-service
spec:
  selector:
    app: aviary-tech
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 80
  type: LoadBalancer
